theme: jekyll-theme-modernist
title: Pixie Folders
description: Set of six minimalist and editable folder icon designs.
show_downloads: true

github:
  zip_url: https://github.com/genesistoxical/pixie-folders/releases/download/1.0/Pixie-Folders.zip
  is_project_page: true
